export const hospitalData = {
  hospital: {
    name: "Bangalore City",
    location: "Bangalore",
    contact: {
      phone: "+91 9732478918",
      email: "info@bangalorecity.com",
    },
    departments: [
      {
        id: 1,
        name: "Cardiology",
        headDoctor: "Dr. Smith",
        beds: 50,
        doctors: [
          { id: 101, name: "Dr. Johnson", specialty: "Cardiologist" },
          { id: 102, name: "Dr. Williams", specialty: "Cardiologist" },
        ],
      },
      {
        id: 2,
        name: "Orthopedics",
        headDoctor: "Dr. Davis",
        beds: 40,
        doctors: [
          {
            id: 201,
            name: "Dr. Anderson",
            specialty: "Orthopedic Surgeon",
          },
          { id: 202, name: "Dr. Brown", specialty: "Orthopedic Surgeon" },
        ],
      },
      {
        id: 3,
        name: "Neurology",
        headDoctor: "Dr. Taylor",
        beds: 30,
        doctors: [
          { id: 301, name: "Dr. Turner", specialty: "Neurologist" },
          { id: 302, name: "Dr. Jane", specialty: "Neurosurgeon" },
        ],
      },
      {
        id: 4,
        name: "Ophthalmology",
        headDoctor: "Dr. Harris",
        beds: 25,
        doctors: [
          { id: 401, name: "Dr. Davis", specialty: "Ophthalmologist" },
          { id: 402, name: "Dr. Miller", specialty: "Ophthalmic Surgeon" },
        ],
      },
      {
        id: 5,
        name: "Dermatology",
        headDoctor: "Dr. Martinez",
        beds: 20,
        doctors: [
          { id: 501, name: "Dr. Hernandez", specialty: "Dermatologist" },
          {
            id: 502,
            name: "Dr. Taylor",
            specialty: "Cosmetic Dermatologist",
          },
        ],
      },
      {
        id: 6,
        name: "Gastroenterology",
        headDoctor: "Dr. White",
        beds: 35,
        doctors: [
          {
            id: 601,
            name: "Dr. Turner",
            specialty: "Gastroenterologist",
          },
          {
            id: 602,
            name: "Dr. Davis",
            specialty: "Gastrointestinal Surgeon",
          },
        ],
      },
      {
        id: 7,
        name: "Pulmonology",
        headDoctor: "Dr. Adams",
        beds: 30,
        doctors: [
          { id: 701, name: "Dr. Miller", specialty: "Pulmonologist" },
          { id: 702, name: "Dr. Brown", specialty: "Thoracic Surgeon" },
        ],
      },
      {
        id: 8,
        name: "Obstetrics and Gynecology",
        headDoctor: "Dr. Garcia",
        beds: 40,
        doctors: [
          { id: 801, name: "Dr. Taylor", specialty: "Obstetrician" },
          { id: 802, name: "Dr. Turner", specialty: "Gynecologist" },
        ],
      },
      {
        id: 9,
        name: "Urology",
        headDoctor: "Dr. Wilson",
        beds: 25,
        doctors: [
          { id: 901, name: "Dr. White", specialty: "Urologist" },
          {
            id: 902,
            name: "Dr. Martinez",
            specialty: "Urological Surgeon",
          },
        ],
      },
      {
        id: 10,
        name: "Endocrinology",
        headDoctor: "Dr. Turner",
        beds: 20,
        doctors: [
          { id: 1001, name: "Dr. Adams", specialty: "Endocrinologist" },
          { id: 1002, name: "Dr. Garcia", specialty: "Endocrine Surgeon" },
        ],
      },
    ],
    equipment: [
      {
        id: 1,
        name: "MRI Machine",
        status: "Operational",
        lastMaintenance: "2023-01-10",
      },
      {
        id: 2,
        name: "X-Ray Machine",
        status: "Operational",
        lastMaintenance: "2023-02-15",
      },
      {
        id: 3,
        name: "Ultrasound Machine",
        status: "Under Maintenance",
        lastMaintenance: "2023-03-20",
      },
      {
        id: 4,
        name: "CT Scanner",
        status: "Operational",
        lastMaintenance: "2023-02-28",
      },
      {
        id: 5,
        name: "Defibrillator",
        status: "Operational",
        lastMaintenance: "2023-01-05",
      },
      {
        id: 6,
        name: "Ventilator",
        status: "Operational",
        lastMaintenance: "2023-03-10",
      },
      {
        id: 7,
        name: "Anesthesia Machine",
        status: "Under Maintenance",
        lastMaintenance: "2023-03-25",
      },
      {
        id: 8,
        name: "Surgical Microscope",
        status: "Operational",
        lastMaintenance: "2023-02-18",
      },
      {
        id: 9,
        name: "Blood Gas Analyzer",
        status: "Operational",
        lastMaintenance: "2023-01-15",
      },
      {
        id: 10,
        name: "Autoclave",
        status: "Operational",
        lastMaintenance: "2023-03-05",
      },
    ],
    bloodBank: {
      bloodGroups: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
      donors: [
        {
          id: 311,
          name: "Ethan Donor",
          bloodType: "O-",
          lastDonation: "2023-02-18",
        },
        {
          id: 312,
          name: "Mia Donor",
          bloodType: "B+",
          lastDonation: "2023-03-25",
        },
        {
          id: 313,
          name: "Elijah Donor",
          bloodType: "AB+",
          lastDonation: "2023-01-10",
        },
        {
          id: 314,
          name: "Amelia Donor",
          bloodType: "A-",
          lastDonation: "2023-02-05",
        },
        {
          id: 315,
          name: "Benjamin Donor",
          bloodType: "O+",
          lastDonation: "2023-03-15",
        },
        {
          id: 316,
          name: "Charlotte Donor",
          bloodType: "A+",
          lastDonation: "2023-02-28",
        },
        {
          id: 317,
          name: "Henry Donor",
          bloodType: "B-",
          lastDonation: "2023-01-20",
        },
        {
          id: 318,
          name: "Liam Donor",
          bloodType: "AB-",
          lastDonation: "2023-03-05",
        },
        {
          id: 319,
          name: "Aria Donor",
          bloodType: "O-",
          lastDonation: "2023-01-12",
        },
        {
          id: 320,
          name: "Ella Donor",
          bloodType: "B+",
          lastDonation: "2023-03-18",
        },
      ],
      requests: [
        {
          id: 6,
          patientId: 601,
          bloodType: "O-",
          unitsRequired: 2,
          date: "2023-02-10",
        },
        {
          id: 7,
          patientId: 701,
          bloodType: "B+",
          unitsRequired: 1,
          date: "2023-03-18",
        },
        {
          id: 8,
          patientId: 801,
          bloodType: "AB+",
          unitsRequired: 3,
          date: "2023-01-25",
        },
        {
          id: 9,
          patientId: 901,
          bloodType: "A-",
          unitsRequired: 2,
          date: "2023-03-05",
        },
        {
          id: 10,
          patientId: 1001,
          bloodType: "O+",
          unitsRequired: 1,
          date: "2023-02-15",
        },
        {
          id: 11,
          patientId: 1101,
          bloodType: "O-",
          unitsRequired: 2,
          date: "2023-01-12",
        },
        {
          id: 12,
          patientId: 1201,
          bloodType: "B+",
          unitsRequired: 1,
          date: "2023-02-22",
        },
        {
          id: 13,
          patientId: 1301,
          bloodType: "AB+",
          unitsRequired: 3,
          date: "2023-03-10",
        },
        {
          id: 14,
          patientId: 1401,
          bloodType: "A-",
          unitsRequired: 2,
          date: "2023-02-18",
        },
        {
          id: 15,
          patientId: 1501,
          bloodType: "O+",
          unitsRequired: 1,
          date: "2023-03-25",
        },
        {
          id: 16,
          patientId: 1601,
          bloodType: "A+",
          unitsRequired: 2,
          date: "2023-01-15",
        },
        {
          id: 17,
          patientId: 1701,
          bloodType: "B-",
          unitsRequired: 1,
          date: "2023-02-28",
        },
        {
          id: 18,
          patientId: 1801,
          bloodType: "AB-",
          unitsRequired: 3,
          date: "2023-03-18",
        },
        {
          id: 19,
          patientId: 1901,
          bloodType: "O-",
          unitsRequired: 2,
          date: "2023-01-20",
        },
        {
          id: 20,
          patientId: 2001,
          bloodType: "B+",
          unitsRequired: 1,
          date: "2023-02-05",
        },
      ],
    },
    ambulanceService: {
      dispatchedRequests: [
        {
          id: 2,
          patientId: 5,
          destination: "City General Hospital",
          dispatchTime: "2023-02-10 02:30 PM",
        },
        {
          id: 3,
          patientId: 8,
          destination: "City General Hospital",
          dispatchTime: "2023-03-05 09:15 AM",
        },
        {
          id: 4,
          patientId: 11,
          destination: "City General Hospital",
          dispatchTime: "2023-01-20 04:45 PM",
        },
        {
          id: 5,
          patientId: 14,
          destination: "City General Hospital",
          dispatchTime: "2023-02-28 11:30 AM",
        },
        {
          id: 6,
          patientId: 17,
          destination: "City General Hospital",
          dispatchTime: "2023-03-18 01:00 PM",
        },
        {
          id: 7,
          patientId: 20,
          destination: "City General Hospital",
          dispatchTime: "2023-01-15 03:20 PM",
        },
        {
          id: 8,
          patientId: 23,
          destination: "City General Hospital",
          dispatchTime: "2023-02-05 10:45 AM",
        },
        {
          id: 9,
          patientId: 26,
          destination: "City General Hospital",
          dispatchTime: "2023-03-10 08:00 AM",
        },
        {
          id: 10,
          patientId: 29,
          destination: "City General Hospital",
          dispatchTime: "2023-01-12 12:30 PM",
        },
        {
          id: 11,
          patientId: 32,
          destination: "City General Hospital",
          dispatchTime: "2023-02-22 05:15 PM",
        },
      ],
    },
    vaccines: [
      {
        id: 1,
        name: "COVID-19 Vaccine",
        manufacturer: "Pfizer",
        dosesAvailable: 500,
        expiryDate: "2023-05-01",
      },
      {
        id: 2,
        name: "Influenza Vaccine",
        manufacturer: "Moderna",
        dosesAvailable: 300,
        expiryDate: "2023-08-01",
      },
      {
        id: 3,
        name: "HPV Vaccine",
        manufacturer: "GlaxoSmithKline",
        dosesAvailable: 200,
        expiryDate: "2023-07-15",
      },
      {
        id: 4,
        name: "Hepatitis B Vaccine",
        manufacturer: "Merck",
        dosesAvailable: 400,
        expiryDate: "2023-09-01",
      },
      {
        id: 5,
        name: "Measles, Mumps, and Rubella (MMR) Vaccine",
        manufacturer: "Sanofi",
        dosesAvailable: 250,
        expiryDate: "2023-06-10",
      },
      {
        id: 6,
        name: "Tetanus, Diphtheria, and Pertussis (Tdap) Vaccine",
        manufacturer: "Pfizer",
        dosesAvailable: 350,
        expiryDate: "2023-07-25",
      },
      {
        id: 7,
        name: "Pneumococcal Vaccine",
        manufacturer: "Johnson & Johnson",
        dosesAvailable: 150,
        expiryDate: "2023-09-15",
      },
      {
        id: 8,
        name: "Meningococcal Vaccine",
        manufacturer: "Novartis",
        dosesAvailable: 200,
        expiryDate: "2023-10-01",
      },
      {
        id: 9,
        name: "Varicella (Chickenpox) Vaccine",
        manufacturer: "Pfizer",
        dosesAvailable: 180,
        expiryDate: "2023-08-20",
      },
      {
        id: 10,
        name: "Hib (Haemophilus Influenzae Type B) Vaccine",
        manufacturer: "Sanofi",
        dosesAvailable: 120,
        expiryDate: "2023-11-05",
      },
      {
        id: 11,
        name: "Rotavirus Vaccine",
        manufacturer: "Merck",
        dosesAvailable: 250,
        expiryDate: "2023-07-10",
      },
      {
        id: 12,
        name: "Shingles (Herpes Zoster) Vaccine",
        manufacturer: "GlaxoSmithKline",
        dosesAvailable: 100,
        expiryDate: "2023-12-01",
      },
      {
        id: 13,
        name: "Typhoid Vaccine",
        manufacturer: "Novavax",
        dosesAvailable: 90,
        expiryDate: "2023-10-15",
      },
      {
        id: 14,
        name: "Yellow Fever Vaccine",
        manufacturer: "Sanofi",
        dosesAvailable: 80,
        expiryDate: "2023-09-30",
      },
      {
        id: 15,
        name: "Cholera Vaccine",
        manufacturer: "Johnson & Johnson",
        dosesAvailable: 70,
        expiryDate: "2023-08-15",
      },
      {
        id: 16,
        name: "Japanese Encephalitis Vaccine",
        manufacturer: "Novartis",
        dosesAvailable: 60,
        expiryDate: "2023-11-20",
      },
    ],
    employeeSchedule: [
      { id: 1, employeeId: 1, day: "Monday", shift: "Morning" },
      { id: 2, employeeId: 2, day: "Tuesday", shift: "Evening" },
      { id: 3, employeeId: 3, day: "Wednesday", shift: "Night" },
      { id: 4, employeeId: 4, day: "Thursday", shift: "Morning" },
      { id: 5, employeeId: 5, day: "Friday", shift: "Evening" },
      { id: 6, employeeId: 6, day: "Saturday", shift: "Night" },
      { id: 7, employeeId: 7, day: "Sunday", shift: "Morning" },
      { id: 8, employeeId: 8, day: "Monday", shift: "Evening" },
      { id: 9, employeeId: 9, day: "Tuesday", shift: "Night" },
      { id: 10, employeeId: 10, day: "Wednesday", shift: "Morning" },
      { id: 11, employeeId: 11, day: "Thursday", shift: "Evening" },
    ],
  },
  medicalStaff: {
    doctors: [
      {
        id: 102,
        name: "Dr. Williams",
        department: "Cardiology",
        patients: [1, 2],
        appointments: [1, 3],
      },
      {
        id: 103,
        name: "Dr. Anderson",
        department: "Orthopedics",
        patients: [4, 5],
        appointments: [2, 4],
      },
      {
        id: 104,
        name: "Dr. Turner",
        department: "Neurology",
        patients: [6, 7],
        appointments: [5, 6],
      },
      {
        id: 105,
        name: "Dr. Davis",
        department: "Ophthalmology",
        patients: [8, 9],
        appointments: [7, 8],
      },
      {
        id: 106,
        name: "Dr. Hernandez",
        department: "Dermatology",
        patients: [10, 11],
        appointments: [9, 10],
      },
      {
        id: 107,
        name: "Dr. Turner",
        department: "Gastroenterology",
        patients: [12, 13],
        appointments: [11, 12],
      },
      {
        id: 108,
        name: "Dr. Miller",
        department: "Pulmonology",
        patients: [14, 15],
        appointments: [13, 14],
      },
      {
        id: 109,
        name: "Dr. Taylor",
        department: "Obstetrics and Gynecology",
        patients: [16, 17],
        appointments: [15, 16],
      },
      {
        id: 110,
        name: "Dr. White",
        department: "Urology",
        patients: [18, 19],
        appointments: [17, 18],
      },
      {
        id: 111,
        name: "Dr. Adams",
        department: "Endocrinology",
        patients: [20, 21],
        appointments: [19, 20],
      },
      {
        id: 112,
        name: "Dr. Garcia",
        department: "Cardiology",
        patients: [22, 23],
        appointments: [21, 22],
      },
      {
        id: 113,
        name: "Dr. Wilson",
        department: "Orthopedics",
        patients: [24, 25],
        appointments: [23, 24],
      },
      {
        id: 114,
        name: "Dr. Martinez",
        department: "Neurology",
        patients: [26, 27],
        appointments: [25, 26],
      },
      {
        id: 115,
        name: "Dr. Turner",
        department: "Ophthalmology",
        patients: [28, 29],
        appointments: [27, 28],
      },
      {
        id: 116,
        name: "Dr. Harris",
        department: "Dermatology",
        patients: [30, 31],
        appointments: [29, 30],
      },
    ],
    nurses: [
      { id: 201, name: "Nurse Smith", experienceYears: 8 },
      { id: 202, name: "Nurse Johnson", experienceYears: 6 },
      { id: 203, name: "Nurse Brown", experienceYears: 5 },
      { id: 204, name: "Nurse Davis", experienceYears: 7 },
      { id: 205, name: "Nurse Anderson", experienceYears: 9 },
      { id: 206, name: "Nurse Taylor", experienceYears: 4 },
      { id: 207, name: "Nurse Turner", experienceYears: 8 },
      { id: 208, name: "Nurse Martinez", experienceYears: 6 },
      { id: 209, name: "Nurse White", experienceYears: 5 },
      { id: 210, name: "Nurse Adams", experienceYears: 7 },
      { id: 211, name: "Nurse Garcia", experienceYears: 9 },
      { id: 212, name: "Nurse Harris", experienceYears: 4 },
      { id: 213, name: "Nurse Wilson", experienceYears: 8 },
      { id: 214, name: "Nurse Turner", experienceYears: 6 },
      { id: 215, name: "Nurse Smith", experienceYears: 5 },
    ],
    employees: [
      {
        id: 1,
        name: "Dr. Smith",
        role: "Cardiologist",
        specialty: "Cardiology",
      },
      {
        id: 2,
        name: "Dr. Williams",
        role: "Cardiologist",
        specialty: "Cardiology",
      },
      {
        id: 3,
        name: "Dr. Anderson",
        role: "Orthopedic Surgeon",
        specialty: "Orthopedics",
      },
      {
        id: 4,
        name: "Dr. Brown",
        role: "Orthopedic Surgeon",
        specialty: "Orthopedics",
      },
      {
        id: 5,
        name: "Dr. Turner",
        role: "Neurologist",
        specialty: "Neurology",
      },
      {
        id: 6,
        name: "Dr. Davis",
        role: "Ophthalmologist",
        specialty: "Ophthalmology",
      },
      {
        id: 7,
        name: "Dr. Martinez",
        role: "Dermatologist",
        specialty: "Dermatology",
      },
      {
        id: 8,
        name: "Dr. White",
        role: "Gastroenterologist",
        specialty: "Gastroenterology",
      },
      {
        id: 9,
        name: "Dr. Adams",
        role: "Pulmonologist",
        specialty: "Pulmonology",
      },
      {
        id: 10,
        name: "Dr. Garcia",
        role: "Obstetrician",
        specialty: "Obstetrics and Gynecology",
      },
      {
        id: 11,
        name: "Dr. Harris",
        role: "Urologist",
        specialty: "Urology",
      },
      {
        id: 12,
        name: "Dr. Wilson",
        role: "Endocrinologist",
        specialty: "Endocrinology",
      },
      {
        id: 13,
        name: "Dr. Turner",
        role: "Cardiologist",
        specialty: "Cardiology",
      },
      {
        id: 14,
        name: "Dr. Martinez",
        role: "Orthopedic Surgeon",
        specialty: "Orthopedics",
      },
      {
        id: 15,
        name: "Dr. White",
        role: "Neurologist",
        specialty: "Neurology",
      },
    ],
    patients: [
      {
        id: 1,
        name: "John Doe",
        gender: "Male",
        dob: "1980-05-15",
        bloodType: "A+",
      },
      {
        id: 2,
        name: "Jane Smith",
        gender: "Female",
        dob: "1992-08-20",
        bloodType: "B-",
      },
      {
        id: 3,
        name: "Michael Johnson",
        gender: "Male",
        dob: "1975-03-10",
        bloodType: "O+",
      },
      {
        id: 4,
        name: "Emily Davis",
        gender: "Female",
        dob: "1988-12-05",
        bloodType: "AB+",
      },
      {
        id: 5,
        name: "Daniel Wilson",
        gender: "Male",
        dob: "1995-09-18",
        bloodType: "A-",
      },
      {
        id: 6,
        name: "Olivia Turner",
        gender: "Female",
        dob: "1982-06-25",
        bloodType: "B+",
      },
      {
        id: 7,
        name: "William Turner",
        gender: "Male",
        dob: "1978-02-08",
        bloodType: "O-",
      },
      {
        id: 8,
        name: "Emma Martinez",
        gender: "Female",
        dob: "1990-11-12",
        bloodType: "AB-",
      },
      {
        id: 9,
        name: "Liam Harris",
        gender: "Male",
        dob: "1987-04-30",
        bloodType: "A+",
      },
      {
        id: 10,
        name: "Ava Garcia",
        gender: "Female",
        dob: "1997-01-22",
        bloodType: "B-",
      },
      {
        id: 11,
        name: "James Brown",
        gender: "Male",
        dob: "1984-07-17",
        bloodType: "O+",
      },
      {
        id: 12,
        name: "Sophia Adams",
        gender: "Female",
        dob: "1994-10-08",
        bloodType: "AB+",
      },
      {
        id: 13,
        name: "Logan Wilson",
        gender: "Male",
        dob: "1970-09-05",
        bloodType: "A-",
      },
      {
        id: 14,
        name: "Mia Turner",
        gender: "Female",
        dob: "1989-03-14",
        bloodType: "B+",
      },
      {
        id: 15,
        name: "Jackson Turner",
        gender: "Male",
        dob: "1998-06-28",
        bloodType: "O-",
      },
    ],
    appointments: [
      {
        id: 1,
        patientId: 1,
        doctorId: 102,
        dateTime: "2023-01-10 09:30 AM",
        department: "Cardiology",
      },
      {
        id: 2,
        patientId: 2,
        doctorId: 103,
        dateTime: "2023-02-15 02:45 PM",
        department: "Orthopedics",
      },
      {
        id: 3,
        patientId: 3,
        doctorId: 104,
        dateTime: "2023-03-20 11:00 AM",
        department: "Neurology",
      },
      {
        id: 4,
        patientId: 4,
        doctorId: 105,
        dateTime: "2023-01-25 03:15 PM",
        department: "Ophthalmology",
      },
      {
        id: 5,
        patientId: 5,
        doctorId: 106,
        dateTime: "2023-02-28 10:30 AM",
        department: "Dermatology",
      },
      {
        id: 6,
        patientId: 6,
        doctorId: 107,
        dateTime: "2023-03-05 01:45 PM",
        department: "Gastroenterology",
      },
      {
        id: 7,
        patientId: 7,
        doctorId: 108,
        dateTime: "2023-01-20 04:00 PM",
        department: "Pulmonology",
      },
      {
        id: 8,
        patientId: 8,
        doctorId: 109,
        dateTime: "2023-02-22 09:15 AM",
        department: "Obstetrics and Gynecology",
      },
      {
        id: 9,
        patientId: 9,
        doctorId: 110,
        dateTime: "2023-03-10 02:30 PM",
        department: "Urology",
      },
      {
        id: 10,
        patientId: 10,
        doctorId: 111,
        dateTime: "2023-01-12 11:45 AM",
        department: "Endocrinology",
      },
      {
        id: 11,
        patientId: 11,
        doctorId: 112,
        dateTime: "2023-02-18 08:00 AM",
        department: "Cardiology",
      },
      {
        id: 12,
        patientId: 12,
        doctorId: 113,
        dateTime: "2023-03-25 01:15 PM",
        department: "Orthopedics",
      },
      {
        id: 13,
        patientId: 13,
        doctorId: 114,
        dateTime: "2023-01-15 05:30 PM",
        department: "Neurology",
      },
      {
        id: 14,
        patientId: 14,
        doctorId: 115,
        dateTime: "2023-02-28 12:45 PM",
        department: "Ophthalmology",
      },
      {
        id: 15,
        patientId: 15,
        doctorId: 116,
        dateTime: "2023-03-18 10:00 AM",
        department: "Dermatology",
      },
    ],
    bloodDonationRequests: [
      {
        id: 1,
        patientId: 1,
        bloodType: "O+",
        unitsRequired: 2,
        date: "2023-01-12",
      },
      {
        id: 2,
        patientId: 2,
        bloodType: "B-",
        unitsRequired: 1,
        date: "2023-02-22",
      },
      {
        id: 3,
        patientId: 3,
        bloodType: "AB+",
        unitsRequired: 3,
        date: "2023-03-10",
      },
      {
        id: 4,
        patientId: 4,
        bloodType: "A-",
        unitsRequired: 2,
        date: "2023-02-18",
      },
      {
        id: 5,
        patientId: 5,
        bloodType: "O+",
        unitsRequired: 1,
        date: "2023-03-25",
      },
      {
        id: 6,
        patientId: 6,
        bloodType: "A+",
        unitsRequired: 2,
        date: "2023-01-15",
      },
      {
        id: 7,
        patientId: 7,
        bloodType: "B-",
        unitsRequired: 1,
        date: "2023-02-28",
      },
      {
        id: 8,
        patientId: 8,
        bloodType: "AB-",
        unitsRequired: 3,
        date: "2023-03-18",
      },
      {
        id: 9,
        patientId: 9,
        bloodType: "O-",
        unitsRequired: 2,
        date: "2023-01-20",
      },
      {
        id: 10,
        patientId: 10,
        bloodType: "B+",
        unitsRequired: 1,
        date: "2023-02-05",
      },
      {
        id: 11,
        patientId: 11,
        bloodType: "O-",
        unitsRequired: 2,
        date: "2023-01-25",
      },
      {
        id: 12,
        patientId: 12,
        bloodType: "AB+",
        unitsRequired: 3,
        date: "2023-02-10",
      },
      {
        id: 13,
        patientId: 13,
        bloodType: "A-",
        unitsRequired: 2,
        date: "2023-03-05",
      },
      {
        id: 14,
        patientId: 14,
        bloodType: "B+",
        unitsRequired: 1,
        date: "2023-03-15",
      },
      {
        id: 15,
        patientId: 15,
        bloodType: "O-",
        unitsRequired: 2,
        date: "2023-02-28",
      },
    ],
    bedOccupancy: {
      cardiology: { occupied: 2, total: 50 },
      orthopedics: { occupied: 4, total: 40 },
      neurology: { occupied: 3, total: 30 },
      ophthalmology: { occupied: 1, total: 20 },
      dermatology: { occupied: 2, total: 25 },
      gastroenterology: { occupied: 3, total: 35 },
      pulmonology: { occupied: 1, total: 15 },
      obstetricsGynecology: { occupied: 2, total: 25 },
      urology: { occupied: 1, total: 20 },
      endocrinology: { occupied: 2, total: 30 },
      oncology: { occupied: 1, total: 15 },
      rheumatology: { occupied: 1, total: 10 },
      psychiatry: { occupied: 2, total: 20 },
      nephrology: { occupied: 1, total: 15 },
      emergency: { occupied: 5, total: 50 },
    },
    medicalTests: [
      {
        id: 1,
        patientId: 1,
        testName: "Blood Count",
        result: "Normal",
        date: "2023-01-12",
      },
      {
        id: 2,
        patientId: 2,
        testName: "X-Ray",
        result: "Clear",
        date: "2023-02-22",
      },
      {
        id: 3,
        patientId: 3,
        testName: "MRI",
        result: "No abnormalities detected",
        date: "2023-03-10",
      },
      {
        id: 4,
        patientId: 4,
        testName: "Ultrasound",
        result: "Normal",
        date: "2023-02-18",
      },
      {
        id: 5,
        patientId: 5,
        testName: "ECG",
        result: "Stable",
        date: "2023-03-25",
      },
      {
        id: 6,
        patientId: 6,
        testName: "CT Scan",
        result: "Clear",
        date: "2023-01-15",
      },
      {
        id: 7,
        patientId: 7,
        testName: "Dental X-Ray",
        result: "No issues found",
        date: "2023-02-28",
      },
      {
        id: 8,
        patientId: 8,
        testName: "Urinalysis",
        result: "Normal",
        date: "2023-03-18",
      },
      {
        id: 9,
        patientId: 9,
        testName: "Blood Glucose",
        result: "Within normal range",
        date: "2023-01-20",
      },
      {
        id: 10,
        patientId: 10,
        testName: "Cholesterol Check",
        result: "Healthy levels",
        date: "2023-02-05",
      },
      {
        id: 11,
        patientId: 11,
        testName: "Thyroid Function Test",
        result: "Normal",
        date: "2023-01-25",
      },
      {
        id: 12,
        patientId: 12,
        testName: "Hemoglobin A1c",
        result: "Good control",
        date: "2023-02-10",
      },
      {
        id: 13,
        patientId: 13,
        testName: "Allergy Test",
        result: "No allergies detected",
        date: "2023-03-05",
      },
      {
        id: 14,
        patientId: 14,
        testName: "Pregnancy Test",
        result: "Positive",
        date: "2023-03-15",
      },
      {
        id: 15,
        patientId: 15,
        testName: "HIV Test",
        result: "Negative",
        date: "2023-02-28",
      },
    ],
    surgeries: [
      {
        id: 1,
        patientId: 1,
        procedureName: "Appendectomy",
        surgeonId: 102,
        date: "2023-01-15",
      },
      {
        id: 2,
        patientId: 2,
        procedureName: "Knee Replacement",
        surgeonId: 103,
        date: "2023-02-28",
      },
      {
        id: 3,
        patientId: 3,
        procedureName: "Brain Surgery",
        surgeonId: 104,
        date: "2023-03-10",
      },
      {
        id: 4,
        patientId: 4,
        procedureName: "Cataract Removal",
        surgeonId: 105,
        date: "2023-01-20",
      },
      {
        id: 5,
        patientId: 5,
        procedureName: "Skin Grafting",
        surgeonId: 106,
        date: "2023-03-25",
      },
      {
        id: 6,
        patientId: 6,
        procedureName: "Heart Bypass Surgery",
        surgeonId: 107,
        date: "2023-01-12",
      },
      {
        id: 7,
        patientId: 7,
        procedureName: "Hip Replacement",
        surgeonId: 108,
        date: "2023-02-22",
      },
      {
        id: 8,
        patientId: 8,
        procedureName: "Gallbladder Removal",
        surgeonId: 109,
        date: "2023-03-18",
      },
      {
        id: 9,
        patientId: 9,
        procedureName: "Prostatectomy",
        surgeonId: 110,
        date: "2023-02-05",
      },
      {
        id: 10,
        patientId: 10,
        procedureName: "Thyroidectomy",
        surgeonId: 111,
        date: "2023-01-25",
      },
      {
        id: 11,
        patientId: 11,
        procedureName: "Lung Transplant",
        surgeonId: 112,
        date: "2023-02-10",
      },
      {
        id: 12,
        patientId: 12,
        procedureName: "C-section",
        surgeonId: 113,
        date: "2023-03-05",
      },
      {
        id: 13,
        patientId: 13,
        procedureName: "Joint Fusion",
        surgeonId: 114,
        date: "2023-03-15",
      },
      {
        id: 14,
        patientId: 14,
        procedureName: "Corneal Transplant",
        surgeonId: 115,
        date: "2023-02-28",
      },
      {
        id: 15,
        patientId: 15,
        procedureName: "Appendectomy",
        surgeonId: 116,
        date: "2023-01-18",
      },
    ],
    billingStatements: [
      {
        id: 1,
        patientId: 1,
        totalAmount: 5000,
        paymentStatus: "Paid",
        date: "2023-01-18",
      },
      {
        id: 2,
        patientId: 2,
        totalAmount: 8000,
        paymentStatus: "Pending",
        date: "2023-02-28",
      },
      {
        id: 3,
        patientId: 3,
        totalAmount: 12000,
        paymentStatus: "Paid",
        date: "2023-03-10",
      },
      {
        id: 4,
        patientId: 4,
        totalAmount: 3000,
        paymentStatus: "Pending",
        date: "2023-01-20",
      },
      {
        id: 5,
        patientId: 5,
        totalAmount: 10000,
        paymentStatus: "Paid",
        date: "2023-03-25",
      },
      {
        id: 6,
        patientId: 6,
        totalAmount: 7000,
        paymentStatus: "Pending",
        date: "2023-01-12",
      },
      {
        id: 7,
        patientId: 7,
        totalAmount: 9000,
        paymentStatus: "Paid",
        date: "2023-02-22",
      },
      {
        id: 8,
        patientId: 8,
        totalAmount: 15000,
        paymentStatus: "Pending",
        date: "2023-03-18",
      },
      {
        id: 9,
        patientId: 9,
        totalAmount: 6000,
        paymentStatus: "Paid",
        date: "2023-02-05",
      },
      {
        id: 10,
        patientId: 10,
        totalAmount: 4500,
        paymentStatus: "Pending",
        date: "2023-01-25",
      },
      {
        id: 11,
        patientId: 11,
        totalAmount: 11000,
        paymentStatus: "Paid",
        date: "2023-02-10",
      },
      {
        id: 12,
        patientId: 12,
        totalAmount: 9500,
        paymentStatus: "Pending",
        date: "2023-03-05",
      },
      {
        id: 13,
        patientId: 13,
        totalAmount: 8000,
        paymentStatus: "Paid",
        date: "2023-03-15",
      },
      {
        id: 14,
        patientId: 14,
        totalAmount: 12000,
        paymentStatus: "Pending",
        date: "2023-02-28",
      },
      {
        id: 15,
        patientId: 15,
        totalAmount: 5000,
        paymentStatus: "Paid",
        date: "2023-01-18",
      },
    ],
    inventory: {
      medicineInventory: [
        { id: "1", name: "Aspirin", quantity: 100, expiryDate: "2022-05-01" },
        { id: "2", name: "Ibuprofen", quantity: 150, expiryDate: "2023-12-25" },
        {
          id: "3",
          name: "Paracetamol",
          quantity: 120,
          expiryDate: "2024-04-20",
        },
        {
          id: "4",
          name: "Amoxicillin",
          quantity: 80,
          expiryDate: "2022-07-10",
        },
        {
          id: "5",
          name: "Ciprofloxacin",
          quantity: 90,
          expiryDate: "2024-03-25",
        },
        {
          id: "6",
          name: "Omeprazole",
          quantity: 110,
          expiryDate: "2021-08-18",
        },
        { id: "7", name: "Lisinopril", quantity: 70, expiryDate: "2022-09-05" },
        {
          id: "8",
          name: "Atorvastatin",
          quantity: 100,
          expiryDate: "2025-06-28",
        },
        {
          id: "9",
          name: "Levothyroxine",
          quantity: 60,
          expiryDate: "2023-11-12",
        },
        { id: "10", name: "Metformin", quantity: 80, expiryDate: "2024-10-08" },
        {
          id: "11",
          name: "Simvastatin",
          quantity: 120,
          expiryDate: "2022-12-05",
        },
        { id: "12", name: "Gabapentin", quantity: 9, expiryDate: "2024-09-18" },
        {
          id: "13",
          name: "Hydrochlorothiazide",
          quantity: 40,
          expiryDate: "2020-02-08",
        },
        { id: "14", name: "Warfarin", quantity: 30, expiryDate: "2023-01-22" },
        {
          id: "15",
          name: "Metoprolol",
          quantity: 60,
          expiryDate: "2024-07-17",
        },
      ],
      equipmentInventory: [
        { name: "X-Ray Machine", quantity: 2, status: "Operational" },
        {
          name: "Ultrasound Machine",
          quantity: 1,
          status: "Under Maintenance",
        },
        { name: "MRI Scanner", quantity: 1, status: "Operational" },
        { name: "ECG Machine", quantity: 3, status: "Operational" },
        { name: "Ventilator", quantity: 5, status: "Operational" },
        { name: "Defibrillator", quantity: 2, status: "Operational" },
        {
          name: "Anesthesia Machine",
          quantity: 1,
          status: "Operational",
        },
        { name: "Operating Table", quantity: 4, status: "Operational" },
        { name: "Autoclave", quantity: 2, status: "Operational" },
        {
          name: "Blood Pressure Monitor",
          quantity: 10,
          status: "Operational",
        },
        { name: "Surgical Lights", quantity: 3, status: "Operational" },
        { name: "Wheelchairs", quantity: 8, status: "Operational" },
        { name: "Stethoscopes", quantity: 15, status: "Operational" },
        {
          name: "Oxygen Concentrator",
          quantity: 6,
          status: "Operational",
        },
        { name: "Hospital Beds", quantity: 30, status: "Operational" },
      ],
      vaccineInventory: [
        {
          name: "COVID-19 Vaccine",
          manufacturer: "Moderna",
          dosesAvailable: 300,
          expiryDate: "2023-04-01",
        },
        {
          name: "Influenza Vaccine",
          manufacturer: "Sanofi",
          dosesAvailable: 200,
          expiryDate: "2023-05-15",
        },
        {
          name: "Hepatitis B Vaccine",
          manufacturer: "GlaxoSmithKline",
          dosesAvailable: 150,
          expiryDate: "2023-06-30",
        },
        {
          name: "Measles, Mumps, Rubella (MMR) Vaccine",
          manufacturer: "Pfizer",
          dosesAvailable: 100,
          expiryDate: "2023-07-20",
        },
        {
          name: "Tetanus, Diphtheria, Pertussis (Tdap) Vaccine",
          manufacturer: "Johnson & Johnson",
          dosesAvailable: 120,
          expiryDate: "2023-08-10",
        },
        {
          name: "Pneumococcal Vaccine",
          manufacturer: "Merck",
          dosesAvailable: 80,
          expiryDate: "2023-09-25",
        },
        {
          name: "Varicella (Chickenpox) Vaccine",
          manufacturer: "Novartis",
          dosesAvailable: 70,
          expiryDate: "2023-10-15",
        },
        {
          name: "Human Papillomavirus (HPV) Vaccine",
          manufacturer: "AstraZeneca",
          dosesAvailable: 50,
          expiryDate: "2023-11-28",
        },
        {
          name: "Meningococcal Vaccine",
          manufacturer: "Bayer",
          dosesAvailable: 60,
          expiryDate: "2023-12-20",
        },
        {
          name: "Rotavirus Vaccine",
          manufacturer: "Roche",
          dosesAvailable: 40,
          expiryDate: "2024-01-05",
        },
        {
          name: "Typhoid Vaccine",
          manufacturer: "Abbott",
          dosesAvailable: 30,
          expiryDate: "2024-02-18",
        },
        {
          name: "Yellow Fever Vaccine",
          manufacturer: "Sandoz",
          dosesAvailable: 20,
          expiryDate: "2024-03-10",
        },
        {
          name: "Rabies Vaccine",
          manufacturer: "Eli Lilly",
          dosesAvailable: 25,
          expiryDate: "2024-04-15",
        },
        {
          name: "Cholera Vaccine",
          manufacturer: "Cipla",
          dosesAvailable: 15,
          expiryDate: "2024-05-01",
        },
        {
          name: "Hib (Haemophilus influenzae type b) Vaccine",
          manufacturer: "Sun Pharma",
          dosesAvailable: 10,
          expiryDate: "2024-06-12",
        },
      ],
    },
  },
};
